include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Disabled rules for weather app - debug logging is essential
    avoid_print: false
    # Some dynamic construction is necessary
    prefer_const_constructors: false

analyzer:
  errors:
    # Suppress deprecated_member_use for withOpacity (Flutter 3.18 migration)
    deprecated_member_use: ignore
